package fsight.youtrack.models.api

data class KPIAggregatedScore(
        val agent: String,
        val total: Float,
        val totalAvg: Float,
        val totalWithViolations: Float,
        val issueTypeSum: Float,
        val prioritySum: Float,
        val levelSum: Float,
        val solutionSum: Float,
        val slaSum: Float,
        val evaluationSum: Float,
        val postponementSum: Float,
        val clarificationSum: Float,
        val issueTypeAvg: Float,
        val priorityAvg: Float,
        val levelAvg: Float,
        val solutionAvg: Float,
        val slaAvg: Float,
        val evaluationAvg: Float,
        val postponementAvg: Float,
        val clarificationAvg: Float,
        val issueTypeCount: Int,
        val priorityCount: Int,
        val levelCount: Int,
        val solutionCount: Int,
        val slaCount: Int,
        val evaluationCount: Int,
        val postponementCount: Int,
        val clarificationCount: Int,
        val violations: Int,
        val details: List<KPIScore>
)