package fsight.youtrack.db.exposed.pg

import org.jetbrains.exposed.sql.Column
import org.jetbrains.exposed.sql.Table

object IssuesTable : Table(name = "issues") {
    val id = varchar(name = "id", length = 64)
    val entityId = varchar(name = "entity_id", length = 64)
    val summary = text(name = "summary")
    val createdDateTime = datetime(name = "created_date_time")
    val createdDate = datetime(name = "created_date")
    val createdWeek = datetime(name = "created_week")
    val updatedDateTime = datetime(name = "updated_date_time")
    val updatedDate = datetime(name = "updated_date")
    val updatedWeek = datetime(name = "updated_week")
    val resolvedDateTime = datetime(name = "resolved_date_time")
    val resolvedDate = datetime(name = "resolved_date")
    val resolvedWeek = datetime(name = "resolved_week")
    val reporterLogin = varchar(name = "reporter_login", length = 1024)
    val commentsCount = integer(name = "comments_count")
    val votes = integer(name = "votes")
    val subsystem = varchar(name = "subsystem", length = 1024)
    val sla = varchar(name = "sla", length = 64)
    val slaFirstResponseIndex: Column<String?> = varchar(name = "sla_first_response_index", length = 64).nullable()
    val slaFirstResponseDateTime = datetime(name = "sla_first_response_date_time")
    val slaFirstResponseDate = datetime(name = "sla_first_response_date")
    val slaFirstResponseWeek = datetime(name = "sla_first_response_week")
    val slaSolutionIndex = varchar(name = "sla_solution_index", length = 64).nullable()
    val slaSolutionDateTime = datetime(name = "sla_solution_date_time")
    val slaSolutionDate = datetime(name = "sla_solution_date")
    val slaSolutionWeek = datetime(name = "sla_solution_week")
    val project = varchar(name = "project", length = 255)
    val issueType = varchar(name = "issue_type", length = 255)
    val state = varchar(name = "state", length = 255)
    val priority = varchar(name = "priority", length = 255)
    val ppVersion = varchar(name = "pp_version", length = 255)
    val qualityEvaluation = varchar(name = "quality_evaluation", length = 255)
    val timeUser = long(name = "time_user")
    val timeAgent = long(name = "time_agent")
    val timeDeveloper = long(name = "time_developer")
    val loadedDate = datetime(name = "loaded_date")
    val qualityEvaluationDateTime = datetime(name = "quality_evaluation_date_time")
    val qualityEvaluationDate = datetime(name = "quality_evaluation_date")
    val qualityEvaluationWeek = datetime(name = "quality_evaluation_week")
    val ets = text(name = "ets")
    val projectShortName = varchar(name = "project_short_name", length = 64)
    val customer = varchar(name = "customer", length = 128)
}