package fsight.youtrack.db.exposed.pg

import org.jetbrains.exposed.sql.Table

object IssuesTable : Table(name = "issues") {
    val id = varchar(name = "id", length = 64)
    val entity_id = varchar(name = "entity_id", length = 64)
    val summary = text(name = "summary")
    val created_date_time = datetime(name = "created_date_time")
    val created_date = datetime(name = "created_date")
    val created_week = datetime(name = "created_week")
    val updated_date_time = datetime(name = "updated_date_time")
    val updated_date = datetime(name = "updated_date")
    val updated_week = datetime(name = "updated_week")
    val resolved_date_time = datetime(name = "resolved_date_time")
    val resolved_date = datetime(name = "resolved_date")
    val resolved_week = datetime(name = "resolved_week")
    val reporter_login = varchar(name = "reporter_login", length = 1024)
    val comments_count = integer(name = "comments_count")
    val votes = integer(name = "votes")
    val subsystem = varchar(name = "subsystem", length = 1024)
    val sla = varchar(name = "sla", length = 64)
    val sla_first_responce_index = varchar(name = "sla_first_responce_index", length = 64)
    val sla_first_responce_date_time = datetime(name = "sla_first_responce_date_time")
    val sla_first_responce_date = datetime(name = "sla_first_responce_date")
    val sla_first_responce_week = datetime(name = "sla_first_responce_week")
    val sla_solution_index = varchar(name = "sla_solution_index", length = 64)
    val sla_solution_date_time = datetime(name = "sla_solution_date_time")
    val sla_solution_date = datetime(name = "sla_solution_date")
    val sla_solution_week = datetime(name = "sla_solution_week")
    val project = varchar(name = "project", length = 255)
    val issue_type = varchar(name = "issue_type", length = 255)
    val state = varchar(name = "state", length = 255)
    val priority = varchar(name = "priority", length = 255)
    val pp_version = varchar(name = "pp_version", length = 255)
    val quality_evaluation = varchar(name = "quality_evaluation", length = 255)
    val time_user = long(name = "time_user")
    val time_agent = long(name = "time_agent")
    val time_developer = long(name = "time_developer")
    val loaded_date = datetime(name = "loaded_date")
    val quality_evaluation_date_time = datetime(name = "quality_evaluation_date_time")
    val quality_evaluation_date = datetime(name = "quality_evaluation_date")
    val quality_evaluation_week = datetime(name = "quality_evaluation_week")
    val ets = text(name = "ets")
    val project_short_name = varchar(name = "project_short_name", length = 64)
    val customer = varchar(name = "customer", length = 128)
}